export const drafts = [
{
id: 0,
finish_reason: "stop",
content: `The man’s eyes were the color of a stormy sky and his hair was the color of a raven’s wing. He was tall and broad shouldered, like a tree, with arms that could hold her tight. She fell in love with him at first sight, and she knew that he felt the same. They had so much in common: they both loved to read, they both loved to travel, they both loved to dance. They spent hours talking about their favorite books, their favorite places, their favorite music. They talked about all the places they wanted to go together: Paris, Venice, Rome… Their wedding day was a glorious affair. It was held in an ancient church with stained glass windows and high vaulted ceilings. The guests were dressed in their finest clothes and jewels glittered on every finger. There were flowers everywhere: roses for love; lilies for beauty; irises for royalty; tulips for devotion; daffodils for innocence; lilies of the valley for purity…`,
},
{
id: 1,
finish_reason: "stop",
content: `In the morning, the girl and the boy were still in bed. The boy was snoring softly, his face buried in a pillow. The girl was staring at the ceiling, her eyes wide open. They had been up all night, talking. The girl had told him about her childhood, growing up in a small town with her father and mother. She told him about how she used to play with dolls and how she used to pretend they were real children that she could take care of. She told him about how she used to imagine her dolls were real children that needed taking care of. She told him about how she had started to imagine that real children needed taking care of. He listened carefully, but he didn’t say much, just asked questions when he didn’t understand something or when he wanted more details or if she wanted to stop talking for a while because it was getting late or if there was anything else that she wanted to tell him or if there was anything else that he wanted to ask her or if there was anything else at all that they wanted to do together now or later or ever again.`,
},
{
id: 2,
finish_reason: "stop",
content: `I was a girl who loved to read. I read every book in the library, every book in the school, and then the books in my father’s study. My father was a writer, so there were many books. He would sit me on his knee and read to me from his work in progress. Sometimes he would let me help him with the research, or even write a sentence or two. The words were like magic, and I was always amazed that they came out of him. One day he took me to meet his publisher at a book fair. They talked for a long time about his work-in-progress, and then they talked about my writing. My father was very proud of me, but he had never told anyone else about my stories before. The publisher said that I should be writing my own books instead of helping my father with his work-in-progress!`,
},
{
id: 3,
finish_reason: "stop",
content: `The first time I saw her, she was standing in the rain, waiting for a bus. I was on my way to the bank, and I stopped to offer her my umbrella. She smiled at me and thanked me for it. I asked her where she was going and she said she was going home. She had just finished her shift at the café down the road. Her name was Lina and she lived with a roommate in a small apartment in the city center, near the university. We talked for a while and then we parted ways, but not before arranging to meet up again later that week. When we met up again, we went to a bar together and got drunk on cheap wine. We talked about everything: our families, our dreams, our childhoods. We talked until it got late and then we went back to her place so that she could sleep off her hangover before work the next day.`,
},
{
id: 4,
finish_reason: "stop",
content: `  She was a woman of the world, and he was a man of the sea. They met in an online chatroom, and spent hours talking about their lives. He was a fisherman, she was an accountant. They talked about their families, their hopes and dreams, their favourite foods. And then one day he asked her to marry him. She said yes. And so they bought a house by the sea, and they had three children: two boys and one girl. They were happy together for years until one day he came home from fishing with no catch at all. He told her that he had lost his way in the mist that morning, but she knew it wasn’t true because she had seen him that morning with another woman on the beach. She didn’t say anything to him about it though; instead she got up from bed and went to the kitchen where she found a large knife with which she cut off her own hand at the wrist and threw it into the sea. As soon as her hand hit the water it turned into a dolphin who swam away into the mist never to be seen again by either of them ever again.  `,
},
{
id: 5,
finish_reason: "stop",
content: `  The man and the woman were both born in the same year, and they both died in the same year. They met in the afterlife, and they fell in love. They spent their days walking through a meadow of lavender, talking about their lives, and making love under a tree of blackthorn. At night, they slept under the stars. One night, as they lay together under the stars, she told him she was pregnant with his child. He was overjoyed at this news, but he was also afraid: what if he died before his child was born? What if he died before his child had grown up? What if he died before his child had found their own love? He told her these things one night as they lay together under the stars. She said nothing for a long time, and then she told him that she would always be with him no matter what happened to either of them. And so it was that when he died on May 5th of that year, she followed him into death on May 6th.  `,
},
{
id: 6,
finish_reason: "stop",
content: `  The man in the dark room was not a man at all, but a woman. She had been born with a condition that caused her body to grow hair on her face and chest, and so she wore the mask of a man, and the clothes of a man, and the mask of a woman. She was in love with another woman who was in love with another man. The two women were friends. They met regularly at the bar near the train station. They talked about their men, how they were both so handsome, how they were both so good to them. One day they went for a walk in the park together, as they often did. They talked about their men again, how much they loved them both equally, how they could never choose between them. And then one of them said “I wish you weren’t wearing that mask” and took it off her friend’s face to reveal her true identity: she was not a man at all but a woman like herself.  `,
},
{
id: 7,
finish_reason: "stop",
content: `  The girl in the blue dress looked at the boy in the black suit, and knew that she was going to marry him. He had a kind face, with soft eyes and a gentle smile. He had a kind heart, too, and he was always willing to help her out. She felt safe with him, protected. She felt loved by him. When he walked her home from school every day, she took his hand in hers and never let go until they reached her house. When he kissed her goodnight on the doorstep, she would kiss him back for as long as it took for them both to get light-headed from lack of oxygen. His kisses were sweet, like honey and sugar-coated almonds; they were warm like hot chocolate on a cold winter’s night; they made her feel safe like a child who has been tucked into bed by her mother after being told that there are no monsters under the bed or in the closet or behind the curtains.  `,
},
{
id: 8,
finish_reason: "stop",
content: `The woman was born with a birthmark that looks like the continent of Australia, and so she had to travel far and wide, from the deserts of the outback to the beaches of Bondi. She had many lovers in her time, but none so special as the one who came from there. He was a water spirit, a kind of mermaid who would come out at night to dance under moonlight. He would dance for hours, his tail undulating in time with his movements. When he saw her for the first time, he thought she was quite beautiful. She was sitting on a rock at the edge of the sea with her legs crossed over one another, a book balanced on her knees. He came up behind her and wrapped his arms around her waist as he whispered in her ear: “I’ve been watching you for some time now; I can’t help but admire your grace.” The woman blushed and turned around to face him. “And what about you?” she said coyly. “Do you have any admirers?” “I do indeed,” he replied as he took her hand in his own and kissed it gently before swimming off into the ocean once more.`,
},
{
id: 9,
finish_reason: "stop",
content: `‘I’m sorry,’ I say, and he doesn’t reply. I look away from him, out of the window, at the passing scenery. It is a dull grey day. We are travelling to the coast. I don’t like the coast. The sea is too big and too blue and too cold for me. But he likes it there, he says it reminds him of home. I look back at him; his eyes are closed and his face is peaceful. He looks like a child when he sleeps; innocent and vulnerable. His hands are small in his lap, with long fingers that are always cold to touch. I had thought his hands were beautiful before; they were so delicate and elegant when he played piano for me on that first night we met in a bar in town. Now they look frail to me, as if they could snap in two at any moment if I were to squeeze them tightly enough or if he got angry with me or if he was to be ill again...`,
},
{
id: 10,
finish_reason: "stop",
content: `We were in love with the idea of each other. She was a novelist, and I was a poet, and it seemed like we would be the perfect couple. We were both fans of the same obscure bands, we both loved art, we both loved to talk about how much we loved to talk. But when it came down to it, our relationship was based on words: how they felt on the page; how they felt in our mouths; how they felt when they left us. And then there was that summer when she went to Europe for three months. I thought I could handle it but I couldn’t. Without her around, my words turned into silence. My poetry became empty words on a page and my novels became nothing more than empty pages. I missed her so much that my heart turned into a block of ice and my words froze inside me until there was nothing left but silence.`,
},
{
id: 11,
finish_reason: "stop",
content: `The day I met you, I was ready to die. The night before, I had been out with friends. We were drinking and laughing and joking about all the things we wanted to do before we died. When it was my turn, I said nothing. I just sat there. My friends kept asking me what it was that I wanted to do before I died, but all that came out of my mouth was a wordless cry of anguish. And then you walked in, so tall and graceful, like a swan gliding across the water. You were wearing a white dress that shone like the moon against your dark skin and your black hair fell down across your shoulders in thick waves. You sat down next to me and asked me what was wrong. And when I told you everything that had happened, you said nothing for a long time. And then you took my hand in yours and told me that one day we would be together forever when we died.`,
},
{
id: 12,
finish_reason: "stop",
content: `  The first time they met, the girl was wearing a white dress. It was the kind of dress you could wear to a wedding, or to a funeral. She had been wearing it for both. The boy was in black, his lips painted red like her lipstick, and the two of them made quite a pair: one dressed in mourning for the end of life, and the other dressed in mourning for the death of love.  They danced together that night, and they danced together every night after that. He would lead her around the dance floor with his hand on her waist, and she would follow him with her eyes closed. Sometimes they’d stop dancing just to hold each other close; sometimes they’d stop dancing just to kiss, their lips locked together until their faces were redder than their lips were painted. They would dance until dawn broke over the horizon, until they couldn’t see each other anymore because of all the light streaming into their eyes.  But one day she didn’t come back for him. She didn’t come back for anyone that day; she was too busy dying in hospital from a heart attack she had suffered during one of their dances earlier that evening. All he could do now was wait until he died too; he couldn't live without her anymore.  `,
},
{
id: 13,
finish_reason: "stop",
content: `  ‘I’m sorry,’ the boy said. ‘I can’t. I just can’t.’ ‘It’s okay, it doesn’t matter, it was a stupid idea anyway. I don’t know why I thought you could help me. You were right, you should never have come here. It was a stupid idea. Stupid, stupid idea! What am I going to do now? I don't know what to do now! What am I going to do now? Oh god, what am I going to do? What am I going to—?’ The girl was sobbing and the boy held her close and rocked her gently back and forth until she had calmed down enough to speak again. ‘What are you going to do? You're going to be okay, we'll figure something out together, no problem.' The girl looked up at him through tear-filled eyes and smiled weakly before burying her face in his chest once more. She felt safe there in his arms; she felt like nothing bad could ever happen as long as he held her like that and told her everything would be okay.  `,
},
{
id: 14,
finish_reason: "stop",
content: `  She was a girl who would sit on the edge of the swimming pool, her legs dangling in the water, her toes twitching in time to some unheard music. I was a boy who would sit on the opposite side of the pool and watch her. We were both too shy to talk to each other, so we sat in silence for hours. Then one day, it began to rain. The sky was grey and heavy with water, and it poured down onto us as we swam around and around the pool. It felt like everything was happening underwater. The raindrops were like fish jumping out of the water; they glinted silver against our skin, they created ripples that ran across our bodies like hands. As I swam towards her, she smiled at me, and I saw that she had teeth made of glass: transparent and sharp as knives. I dived into the water before she could cut me with them.  `,
},
{
id: 15,
finish_reason: "stop",
content: `  The boy looked at the girl and the girl looked at the boy. They were both looking for something, but neither knew what. They tried to talk about it, but they never got far before giving up. The boy tried to tell the girl he didn’t know what he was looking for, that if she wanted to leave him she should just go and not worry about him. He said this because he thought that if she left him then at least he could stop looking for something that wasn’t there. The girl said nothing in response, because she was too busy thinking about how she didn’t know what love was supposed to feel like or look like or taste like or sound like or smell like or feel like and whether it would be possible for her to learn how to love someone else when she couldn’t even figure out how to love herself. So they carried on living together, day after day, month after month, year after year, without ever saying a word about what they were both looking for.  `,
},
{
id: 16,
finish_reason: "stop",
content: `  The girl had never been to the beach before. As she entered the water, she was struck by the sudden coolness of it, a sensation that was both familiar and alien; her mother had told her that water could be cold sometimes, but it wasn’t supposed to feel like ice. The girl thought of her mother as she waded deeper into the ocean, until the water came up to her waist. She closed her eyes and took a deep breath, but when she opened them again, all she could see was blackness. She felt for the bottom with her feet, but there was nothing there. She began to panic; she couldn’t breathe in this cold blackness. Her mother had told her about drowning once; how it would feel like being wrapped in a heavy blanket that you couldn’t fight your way out of. But where was her mother now? The girl reached out for something to grab onto, but there was nothing there. And then suddenly there were arms around her waist, pulling her up until she broke through the surface of the water and took in a deep breath of air. It wasn’t until later that night that she realized what it felt like to hold someone who loved you so much they would never let you go.  `,
},
{
id: 17,
finish_reason: "stop",
content: `She was a girl born under the Northern Lights, and so, when he saw her for the first time, her skin glowed with the light of a thousand stars. And as she grew from girl to woman, her skin only shone brighter. It was some years before he worked up the courage to ask if he could touch that light, and she allowed him a brief caress before abruptly turning to walk back home. He followed her there in the dark, where they sat by the fire and talked for hours on end about their dreams. She told of how she wanted to be an artist, but that she didn't have any talent for it. He told how he wanted to be a musician, but that his band had broken up. Before they knew it, they were talking about their past relationships and their current situations: how one had been a housewife and mother until she was twenty-nine; how one had been in love with someone who didn't love him back; how one had been single for more than half of his life; how one had believed in marriage before realizing it wasn't what he wanted at all. They talked about everything but themselves until there was little left to say.`,
},
{
id: 18,
finish_reason: "stop",
content: `When the man came back from the war, he had lost more than his leg. His eyes were always downcast, never meeting their gaze; his mind was always elsewhere. The woman tried to get him to talk, but he would only say she was beautiful and that he loved her. She wanted to ask where he had been and what had happened, but she thought it best to leave it alone. And so they lived in silence for many years, until one day when the man said something new. The woman was washing dishes when she heard a strange sound coming from the other room. It sounded like crying. She turned off the faucet and crept into the living room, where she saw her husband sitting on the couch with a kangaroo next to him. The kangaroo was hugging him as if it were a child and crying into his chest. The woman didn’t know what to do, so she sat at the edge of the couch and stroked its little head while whispering comforting words in its ear until it fell asleep in her husband’s lap. That night they made love for the first time since before all of this happened; afterwards, they lay there together with their arms wrapped around each other and slept through until morning.`,
},
{
id: 19,
finish_reason: "stop",
content: `  At first, he thought she was a flower, a lily floating in the pond. When he saw her face, he thought she was an angel. She was both, and more: a goddess of the water. A nymph. The children were delighted when they found her, their secret friend. They swam with her after school and told her about their lives in whispers, but never about the bad things, like the bullying or when their father lost his job. The nymph only listened and smiled at them with her blue lips that tasted of saltwater and honey. They would never have to worry about anything again with the nymph watching over them. One day, as they walked home from school together, two of the bullies pushed them into an alleyway where no one could see them. Then they started calling them names and pinching their cheeks until they were red and raw. The nymph tried to get them to stop but it only made the bullies angrier so she turned around and fled back towards the pond as fast as she could go. When she reached it she sank into the water without looking back at her friends who were still being bullied by those boys that called themselves men.  `,
},
{
id: 20,
finish_reason: "stop",
content: `  It is the day of the wedding, and the bride is nervous. “What if I forget my vows? What if he doesn’t show up? What if it rains?” The mother of the bride looks at her daughter and smiles. “Don’t worry, darling. I know you will remember your vows, and it won’t rain on your special day. I also know that you will never be as happy as you are today. That is what I want for you: happiness, but only today. None of tomorrow, none of next week or next year: just today.” The bride nods and lets her mother kiss her on both cheeks before she leaves to meet her groom at the altar. As soon as she steps out into the cold night air she sees him waiting for her under a street lamp; his eyes are bright with love and excitement, and he takes both of her hands in his own as they walk down the aisle together to begin their lives together. And that is what happens: they live happily ever after right now, on this one day; there will be no more days like this one for them but it doesn't matter because this one day is enough to last them a lifetime and beyond...  `,
},
{
id: 21,
finish_reason: "stop",
content: `  In the old days, he had been a great warrior. He could run for hours without tiring, and he could hurl spears with such accuracy that even the most powerful of enemies would fall before him. But then he fell in love with the wrong woman. She had hair like a waterfall and skin as smooth as a watermelon. He was so taken by her beauty that he forgot about his duties, and soon his people were starving. They turned on him, eventually driving him out of town. Outcast, he wandered aimlessly until he came upon a peach tree in full bloom. He sat under it for days, watching the petals fall and feeling his heart grow heavier by the second as his eyes glazed over with tears. The peach tree was so moved by the warrior’s devotion that it called to its sister trees to help it make one last gift for the man: a bowl made entirely out of glass that would never stain or shatter because it was made from his tears.  `,
},
{
id: 22,
finish_reason: "stop",
content: `  I used to think that if you could just get all the numbers right, you'd be able to predict the future, and time itself wouldn't mean anything. As I lay in bed, staring at the ceiling, listening to my lover’s breath rise and fall like a tide, I thought about how we had met: I was walking along the beach one sunny day when I saw a pretty girl with tangled brown hair. She was wearing a faded dress and her shoes were bare. She told me she had come from another time, another world where she had been floating in space on a chunk of ice. We fell in love on the spot and were married two weeks later. There was a problem with her visa but we got through it eventually. We moved into this apartment together; it was small but adequate for two people who didn't spend much time there. It's more of a home now than it ever has been before because we're both here, together.  `,
},
{
id: 23,
finish_reason: "stop",
content: `  The woman is a stranger to herself, she’s sure of it. She has no idea who she is, where she’s from, what her name is. She knows that there are two men in her life, and that they both love her. One of them is called David. He works at a bank and smiles all the time when he sees her. The other one is called Tom. He has a beard and doesn't smile as much as David does when he sees her, but she loves him more because of it. She thinks that Tom might be the one who loves her more than David does.  One day, the woman comes home to find that David and Tom are fighting over her in the kitchen. She’s scared by this, because they’ve never fought over anything before, and they have never fought over her before either. They are shouting at each other in a language that she doesn’t understand, but they both seem very angry about something. Then there is a horrible sound like breaking glass, and then everything goes very silent – so silent that the woman can hear herself breathing for the first time in years – and then Tom screams out loud like someone has sliced him open with a knife – or broken a bottle on his face – which makes the woman scream too – which makes David scream too.  `,
},
{
id: 24,
finish_reason: "stop",
content: `  The boy feels like a prisoner in his own body. His skin is too tight, his bones are too tall, his joints are too stiff. The man who holds him captive is a stranger, and yet he is the only one who knows him. He knows how to make him smile, how to make him laugh. He knows how to make him feel good about himself. He loves him as only a father can love a son, and yet the boy cannot remember what it was like to have this man's blood running through his veins. He remembers nothing but the feel of this man's hand on his face, on his hair, on his shoulder. The boy does not know whether he loves or hates this man who has raised him from infancy with such tenderness and ferocity. Sometimes he feels like he should hate him, but then the man will smile or laugh and the boy forgets why he was angry in the first place.  `,
},
{
id: 25,
finish_reason: "stop",
content: `  The girl was born with a silver spoon in her mouth. Her parents were wealthy, and they had a country mansion with a large garden, the kind of garden where you can do anything you like, including building your own tree house. One day, when she was playing on the ground floor, she found her way to the attic and discovered a dusty old trunk that her parents had forgotten about. It was full of old toys and books. She took out a small wooden doll’s house and placed it on top of her head, pretending it was a hat. She took out a frayed book with no cover and started reading aloud from it: "Once upon a time there lived...” She couldn’t read very well, but she loved hearing the sound of words coming from her mouth. But then she heard footsteps approaching, so she quickly put everything back in the trunk as best as she could and closed it. The footsteps were getting closer. Then the door opened and there stood her mother. “What are you doing?” Her mother asked sternly “Nothing” said the girl “I just saw this trunk here and I wanted to see what’s inside" “Did you find anything interesting?” Her mother asked “No" said the girl "There is nothing interesting in here" Her mother nodded slowly "Then maybe you should go outside for some fresh air" And so they went outside together to play in the garden.  `,
},
{
id: 26,
finish_reason: "stop",
content: `The couple sat in the corner of a bar, where the music was loud and the drinks were cheap. He told her everything. He told her about how he had been living on the street for years, how people would avert their eyes as he held out his cup to them. He told her about how he had only boarded up the windows of his apartment after it was broken into, how no one even noticed him when they walked by. He told her about how he had stolen this coat from a shop, and that hat from a man who'd been passed out in an alleyway. She listened to all of this quietly, nursing her drink when she wasn't looking at him. When they walked outside, she took off his coat and handed it back to him. She took off his hat and handed it back to him as well. As she walked away from him down the street, she didn't look back once to see if he was following her or not.`,
},
{
id: 27,
finish_reason: "stop",
content: `The old couple lay under the covers, their faces pressed together like a book. They were so close they could feel each other’s breath on their lips. The woman smiled, and her husband smiled back. It almost looked like they were kissing, but they weren’t; instead, they were breathing each other in, the oxygen flowing into their lungs and mingling with the carbon dioxide from their exhalations. She closed her eyes. She could hear him humming softly in her ear, a song she had been humming to him every night since they had first met, forty years ago. He was singing it now because he couldn’t sleep without hearing it from her lips one last time before he went out for the night. “I’ll be home again tomorrow night…” His voice grew softer as she drifted off to sleep. She knew that he would be there again when she woke up; she knew that he would still be breathing in her breath and looking at her with his big blue eyes as if to say “I love you so much”; she knew that he would still be there when she died ten years later, of heart failure while sleeping next to him; but for now – just this little moment – she knew that the man was all hers and that no one in all of the world would ever have him but her.`,
},
{
id: 28,
finish_reason: "stop",
content: `She was a widow, and he was dead. Once, they had been a married couple, but now that was a distant memory. Now, she lived in the cemetery where he had been buried. It made perfect sense to her that she would live here, among the dead. When they were married, he had always been so affectionate. At night he would hold her in his arms and whisper of his love for her. She would lie there watching him sleep until it became too painful to watch him not breathe anymore. But she held onto him as long as she could. Then, one night when they were asleep together, a fire broke out in their house. He never woke up; it was as if he knew what was happening before it happened. She was able to escape with her life. Now when she went to visit his grave, she never stayed for very long because it hurt too much to see his name carved in the stone beside the dates of his birth and death. The rest of the inscription said “Beloved Husband” but all that really mattered to her were those dates: 1955-1977`,
},
{
id: 29,
finish_reason: "stop",
content: `  ____ A love poem by a cicada. ____ The poet is in love with a woman who isn't there. She is in his dreams, always sitting right next to him, but he knows she's not real. When he wakes up, the bed is empty and cold. He spends his entire day trying to find her, but he can never seem to locate her scent. He thinks maybe he could catch her if he reads his poems too loudly, so loudly they echo down the halls of the hospital where she works, but as soon as he gets home from work she's already asleep, lost among nightmares of a life she never had. And when morning comes she is gone again, and all that remains are crumpled sheets and an empty house. The poet thinks about going from room to room until he finds her resting in some corner, or perhaps even under the table or behind the couch (he has checked there already), but every time it's out of reach before he even notices something's changed. And if you can hear him weeping in the background you might think it's just some seagull flying past your window on its way to your neighbor’s trashcan at night. But really it’s probably just someone crying into their pillow because they feel like they are dying inside and have no idea why… `,
},
{
id: 30,
finish_reason: "stop",
content: `  I had been chasing my love around the world for three years. She was at a literary festival in London, I was in Prague, and we were sending each other emails daily, quipping about the city, telling each other how much we missed each other. The next day she would be in Paris, and I would be in Beijing. We never planned to meet up. To see her face-to-face was too painful, too much of an acknowledgement that we were not together. And then one night, she emailed me saying that she was coming to Beijing and wanted to see me. With shaking hands, I booked a room at the hotel where she was staying. When she arrived the next day, I didn’t recognise her because her face had changed so much since the last time we saw each other: it had aged by twenty years. But it didn’t matter; all that mattered is that she was here with me now and nothing else mattered anymore.  `,
},
{
id: 31,
finish_reason: "stop",
content: `  Every day for the past three years, the man has brought his lover to this very spot. He has brought her here, to the top of the hill, where they can look over the city and pay homage to the mountain that looms behind them. He tells her how he met God in a dream, how he created her in His image, how He told him that love was worth clinging to. Down below their home is a city of people who have been touched by God’s grace: an old man who can balance a cup on his nose; a teenage girl who can bend metal with her bare hands; a baby boy whose tears are so hot they burn holes in his mother’s breast. The man has told his lover about each and every one of them, about each and every miracle. She listens without comment: it is not love that compels him but duty.  `,
},
{
id: 32,
finish_reason: "stop",
content: `The young couple began their flirting with a heated debate about the existence of the soul. The girl had an almost religious belief in it and was on a personal quest to prove its existence. He argued that the soul was an invention of religions to keep people under control. It annoyed her when he refused to believe in any higher power other than himself, though she enjoyed dining with him even when they argued, and so sought ways to change his mind. When she talked about the soul, he’d reach into his pocket, pull out a small piece of quartz and tell her that it had been given to him by his grandmother who’d told him that if he ever found someone who could hear the music within it then he would know that he had met his soul mate. Grinning at her with those bewitching green eyes, she would hold each end of the tiny bead between her fingers and ask if she could hear anything and he would open his mouth and say ‘yes’ as if making love.`,
},
{
id: 33,
finish_reason: "stop",
content: `Her name was Linh, but she was often The Dragon. She would lie on her back, sword drawn on the floor beside her, and as I passed by, my calf muscles would tense as though they could feel the wind from her sword-stroke. She’d often shout at me and say that I needed to be more proactive about seeking out my opponent. “What do you think I’m doing?” I’d reply, before passing her. “I am your opponent!” she’d tell me and laugh, before swinging the sword again. At first, when she spoke to me as if we were enemies in battle, it came across as a little coldly mechanical: maybe even a little intimidatingly so. But soon I got used to it and started to look forward to her attention at every opportunity. To know that someone else was taking an interest in my progress gave me wings and a sense of purpose that had been previously lacking in my life – a sense of purpose inspired by the greatest dragon slayer of all time…`,
},
{
id: 34,
finish_reason: "stop",
content: `When the man was born, his father wrote him a poem: ______________________________________________________ You are the son of a rebel, but the rebel was weak. And you are my son. But what can I do? It’s as if heaven had made a mistake, and you were sent here by mistake. When your mother died, I felt like hell had made its own mistake. And now I’m losing you to one of its creatures. Maybe it’s time for me to die too. ______________________________________________________ For years after that, the man didn’t know why his father had hated him so much, but now he knew that it was just love. And he couldn’t hate his father any more than he could love his wife. He knew this poem better than how to write his name in full. He knew not to use capital letters or punctuation marks because they didn’t exist in heaven or hell either way; they were both places where there was nothing at all out of place. He suspected that in those places even this poem might feel misplaced but he didn’t mind because he wrote it anyway; at least no one else could write anything worse about them than this poem had been able to say about him when he was still young and trying too hard to be perfect and no one around him could complain because everyone else was just as fucked up as they were anyway.`,
},
{
id: 35,
finish_reason: "stop",
content: `  It was the hand that did it. The hand with its bony, work-hardened fingers that gripped my forearm and propelled me in a rush towards the hills where a chain of young boys were gathering, their scrawny legs planted firmly apart. I didn’t know why or what for. I have a tingling feeling in my arm from where the hand gripped it, and my palm still shivers when I think of it. The boys know better than to let your ragged silences or useless questions get in their way. They’ve got a job to do: faces to smash and skulls to crack and they’re not going to let anyone get in their way. The last time we did this I was too slow bringing my hands up to protect myself, and before I knew what was happening my nose was broken and blood was streaming down my chin onto the ground beneath us. The boys were busy filling the ever growing cart full of corpses while screaming madly with delight; they paid no heed to me.  `,
},
{
id: 36,
finish_reason: "stop",
content: `  Thinking of her is like a bad drug for the guy. She’s always on his mind, night or day, he’s just not sure which. He feels like he’s burning up when he thinks of her, like his heart is going to freakin’ explode. To calm himself down when he gets these thoughts going in his head, he does something physical. He runs five miles, or starts a fight with the next schmuck to look at him funny. When he thinks of her in school she makes her way through the day until lunch and then she sees him across the cafeteria. She catches his stare and locks eyes with him for a little while as she feels a familiar thrill rush through her body starting from her temples and finishing at the very bottom of her toes and then shooting back up to the top of her head so that she feels light headed, almost high .Then they go about their days until they go home but once there all bets are off and it's time to get ready for bed because they have school again tomorrow  `,
},
{
id: 37,
finish_reason: "stop",
content: `  It was an unromantic way to meet. He had been beside himself with worry ever since he saw her sitting so forlornly on the bench. Her companion was taking some time and he didn’t know what to do, so he sat down next to her. They didn’t speak for a long time, both too shy to say anything. But they sighed in unison and their hands clasped at the same moment, like they were unwilling to let go of each other. Looking at his profile, she knew that he looked a little sadder than most people she knew. His dark eyes were melancholy and set in a face that seemed carved by time into lines of inconsolable grief. But suddenly her heart surged with a strength she had never known before and she wanted to be his joy again, everyone’s joy, with their laughter echoing off the walls of nearby buildings, bouncing off the gutters and into the sky. No one should be sad when they could laugh like this! ‘I am sorry for your loss’, she said finally as she squeezed his cold hand gently with hers.  `,
},
{
id: 38,
finish_reason: "stop",
content: `  I loved him the moment I saw him. I had left my heart at home, but he had a box of matches. He offered me a light. As our skin touched, his match went out and he smiled a smile that let me know he understood what it was like to be restless, like me. We were married six weeks later in a small ceremony on the beach as the sun set over the horizon, a vision so magnificent that for one second my heart forgot to feel empty.  Throughout my childhood my mother warned me about men like him. She is very religious and believes that all things can either be used or cast away. My mother is like a sea sponge, absorbing everything from her surroundings like water fills every crevice in its porous texture until there is no more room to add another drop of water and no more room for air and it becomes saturated with its own self-loathing until it cannot bear the weight of its own existence any longer and it sinks to the ocean floor and dies in agonizing surrender. What had she absorbed about men that she could so easily predict our fate? Life is not an inevitable march forward, but sometimes joins us with our destined partner before we even know they exist - can we truly expect anything else? The man upstairs plays out his symphony for us; we are merely instruments in his odd orchestra.  `,
},
{
id: 39,
finish_reason: "stop",
content: `They were architects, but they spent their lives building the smallest things: trinkets that fit in a palm of a hand, roses that could rest in someone’s hair. But when they were married, they began to build bigger things – castles with faithful sentinels for servants and turrets with carved columns, waterfalls flowing with emeralds and replicas of themselves; redoubts where their enemies would sleep forever; towers big enough for all the winds of time to sweep through. They built these structures deep in the woods where no one else would see them, and their hands slowly became hard from pushing against the canvass before them. At night, they slept on separate sides of the room; he on a bed whose frame was made from two pieces of oak that had been sawn into shape by his own hands; she floating on a raft made out of glass plates inlaid over an invisible flotation device. Once every month or two months or three months he would lay her down on this raft-bed and kiss her as she floated across the night sky towards their secret mountainside castle.`,
},
{
id: 40,
finish_reason: "stop",
content: `The colours of the rainbow; my love for you, returned. When I was a small boy, I would press my face up against the sweetshop's windowpane and gaze on its array of colourful sweets — reds like strawberries and yellows like lemon, oranges like sunsets and purples like thistles. On the shelf next to them lay an array of shiny chocolates in striking hues of green, blue, pink and brown. A boy next to me asked his mother why the chocolates were bound so close together inside the glass case, as if they had all been made in one mould or something. “Because they don't mix with one another,” she replied. I could barely contain my excitement at her words and ran into my father's arms crying out that I want an Apollo Bar - round and purple as a grapefruit with thick vanilla creaminterwoven through it — but when I got back to the glass case it must have sold because there was one missing from its ranks. My mother told me that things were too often not as simple as we wanted them to be. “You should have just asked for another chocolate altogether then!” My mother was always full of good advice and always right but that was later on in our lives; at this moment we were simply two children staring up at a busy glass case filled with gaudy, multicoloured confectionery, ignorant to what lay ahead for us in life.`,
},
{
id: 41,
finish_reason: "stop",
content: `He desires her like he desires books to read, as if the two are inseparable entities. But when they're together there are no words between them, only heavy, rapid breath and the closeness of their bodies. She will kiss his scars as if they were her own, all the while tracing a path from one to another with her fingers. Seasons pass and somehow he never manages to leave here, this small town with its small house up on a hill overlooking the sea, but everything is okay. When he watches her sleep at night he thinks of the young boy she used to be; she still has that cute mole under her ear but now it's surrounded by peach fuzz. He longs for another short adventure with her and soon she will want him too, like he already wants her back. It's like looking into a window at night to see the future illuminated by love's bright glow; it will happen inevitably and suddenly in an instant without warning or preparation and will end just as abruptly with hope evaporated into thin air.`,
},
{
id: 42,
finish_reason: "stop",
content: `They were both named for islands, one with a population of over ten thousand, the other a sea-faring legend that came to grief in a hideous storm. The younger woman’s father always thought it was cruel to call his daughter after such a tragedy. But he forgot, every time he called her by her name, that she was also one day destined to suffer it herself. One day she lost a tooth and they played havit (a children's game where you pick another child and shake hands.) She saw the boy's mood change as soon as they shook hands and his grey eyes froze over in pain. He took the tooth that had been hers all along, the tooth that had been stuck into the ground beside him and hidden with his brother's so long ago. She sobbed noisily and clutched her hand; he fled without making eye contact. To this day she wonders what went through his mind when he saw hers; whether it reminded him of something else too; whether it brought back memories he didn't want to relive; whether she looked too much like someone from his past who no longer made him happy.`,
},
{
id: 43,
finish_reason: "stop",
content: `The late summer of love was the first time I ever laid eyes on you, sitting outside The Empire with your Mary Quant dress and mod hair. I never guessed a girl like that would pay me any mind, but she did. She told me to smile and I did. And when we kissed it tasted like blackberries, as if we had been snacking on them all summer. When we smiled at each other it was in code, her cheeks triangulated by mine — success! It's funny how quickly you forget how much time you actually spend together; my memory of your face has become pixelated and runny from so many afternoons spent pouring over the same yearbook photo. On the tenth anniversary of our meeting that teenage spy girl ran off to Washington to follow a band around for a while, now I kid you not: next thing I hear she's married to an art critic in New York City; still can't picture you as an art critic’s wife — seems too refined for such a mundane job description (which is probably just more grist for her -our- mill.) She's got herself more images up online than are really necessary; twenty years now and still not here.`,
},
{
id: 44,
finish_reason: "stop",
content: `They had met at a party, in the basement of an old building, a student club with a red, velvet carpet and creaking floorboards. She was his hero. She painted the blood that streaked across superheroes on the pages of his comic books. He walked up to her after a while, when he’d finished chatting to some friends and she sat alone in the corner surrounded by empty bottles of vodka. He had trouble looking into her eyes; he kept squeezing his own shut or looking at them from slightly below, like worms swimming in dark water. When she finally laughed at something silly he said (he can’t remember what it was; it probably wasn’t funny), his whole body felt warm with pleasure. And then they walked home together, through empty streets and wet grass, in silence. All week she stayed in his head like some kind of disease or weird kind of fever. At two in the morning on Sunday he got up again and found her on Facebook—that’s when they realised that they both worked for the same publisher—they texted all night long until finally there came a time when neither could think of anything new to say. By then they were too invested anyway; all that was left was to meet up again, if only to get some sleep and finish talking about where they liked drinking coffee and what movies made them cry and stuff like that.`,
},
{
id: 45,
finish_reason: "stop",
content: `  When I met her she was a half-eaten orange, lying with her peels sprawled all around her like discarded metal petals. She wasn’t human then, but I didn’t care. Oranges are the best lovers anyway: so fragile and juicy, they have the sweetest skin and tender sides that you can pin to your lips. I knew she was not what she seemed: a sweet angel fallen from the Heavens, but it didn’t matter to me. It wasn't until after I'd eaten every part of her out of existence that she told me that if you don't die when you're bitten by a vampire, you become one yourself. I told her that vampires are impure creatures full of ill intentions; that they are not like the fair children of sun-drenched days too vivid and unreal to be true; but for all my scare talk there was nothing to say about the hunger inside me: my heart wanting nothing more than to be swept off its feet by a kind stranger with devious intentions.  `,
},
{
id: 46,
finish_reason: "stop",
content: `  I tried to be like the other kids, to fit in with the boys, but every day ran into more tricks designed to exclude me until I was alone, excluded from the games and cajoled into helping on the farm. My grandmother was proud of the farm. She raised roses there and grew her own food, dug up potatoes and carrots from the earth. All work and no play makes Jack a dull boy, she said, so she taught me how to milk and killed fish for dinner. My mother didn’t come home; she’d got hooked on men who liked skinnier girls and went to jail for trying to sell my sister into prostitution when she was just sixteen years old. Sometimes we’d go visit them both in jail. I’d sit next to her on the bed while they talked through a metal grille like a goddamn prison movie. Sometimes we ate food off trays with plastic cutlery: beef stew and cornbread made with lard; just pretending none of it was real.  `,
},
{
id: 47,
finish_reason: "stop",
content: `  When we met, she was wearing a monocle that made her look like a racoon. I took it off in a fit of passion, but the moment I did she was transformed and no longer beautiful. I felt like the Prince who awoke the sleeping beauty with a kiss. When we kissed for the first time, my beard scratched her chapped lips and I almost cried. It put me off kissing boys for a long time, but I was smitten nonetheless. Even though she spent more money gambling than she earned from her hard job as an accountant and got away without paying at least once every two weeks, I fell for her just the same. The way she looked at me with those wide brown eyes, it was so sincere you’d think she really could see through me to my heart (which shattered into a million pieces behind my ribcage). She’s been leaving smaller pieces of herself ever since we broke up six months ago.  `,
},
{
id: 48,
finish_reason: "stop",
content: `  “I loathe silence.” She remembers when he said that to her, quietly, his thin black line lips barely moving. He had just gotten over a breakup and was really into her, and told her this in one of those moments they had alone together in the apartment he said was his but really wasn’t. It got awkward between them afterwards, and neither of them ever mentioned how things weren’t that serious anyway and both of them could stand to give more to life than they were used. Once he flew into a rage because she hadn't noticed when he changed the station on their radio, slammed a vase or two for effect, locked himself up in his room with a bottle of booze – all things they didn’t need – sent a scare through the whole place, frightened the cat shitless, that small grey-white kitten she kept as nine lives insurance in case something terrible happened. The main thing she remembers, though, is how only then he talked about what was going on inside him; it took screaming at everyone else not to for him to find the courage to say two words about his feelings: my fear of dying alone… `,
},
{
id: 49,
finish_reason: "stop",
content: `  He tells her that it’s a once in a lifetime opportunity, more important than anything else he does. She says that she understands, but then turns away, hugging her pillow tightly to her chest as she smokes the inside of the bed sheets. She prays every time the fight starts again, begs God to take this all away from her; days and days of nothing but smoke and ash, cigarette burns that appear on her breasts like stars. What’s left when the ashen remains are swept up and thrown away? When you strike a match you destroy whatever is lying there in front of you. So much more disappears than just what you have first thought: flesh becomes unruly ash that can’t be collected up for yourself or anyone else with whose stick you might be matchmaking; skin becomes so brittle it breaks like paper underneath your lover's tender touch; bones can never be saved for later use no matter who is its guardian. No one lives long enough to make love with ash except phoenixes, who live on flames they kindle themselves. Everyone else has to settle for skinned knees or blackened fingers or torn ears…and ash isn't good conversation anyway.  `,
},
{
id: 50,
finish_reason: "stop",
content: `Overheard on a bus, a man tells his wife that he loves her. She nods, and then, under her breath: “It’s complicated these days”. He turns to look at her during the lull between bursts of chatter. It’s easier now, because everyone is too busy looking at their phones. She, gently running a hand over his shoulder and neck, understands that this has absolutely nothing to do with him (and everything to do with aging). Over time, light begins to register on sunglasses as brightness decreases: beige mixed with honey – something one could drown in and fall into; vanilla mixed with malt: color so like herself it was simple to lose herself – almost like ending up in a rippled pond; chartreuse mixed with blueberry: something exclusive for those who have always been good in spite of their worst instincts; rose petal – darkening into geranium which then blends seamlessly into plum so dark that it spread fresh violets across the spectrum by its shadow. The only memory he possess is calling out loudly as they enter the tunnel together for the last time. She lies spent by his side whispering “Just don't die on me yet” against his shoulder ------------- Lights down, please! Thank you!!! ---------------`,
},
{
id: 51,
finish_reason: "stop",
content: `When I met my soulmate we were both in the process of trying to make some sense out of our in-betweennesses: the writer at a science convention and me at painting, both listening earnestly to our own audiences, elaborating on current theories and coming up with new things we thought should be tried. Our approaches seemed almost identical, but we did not quite meet because she was trying to write something novels would be written about, and I could only paint with my hands. Nearly forty years later (and now both retired) we crossed paths again at an online museum for paleontology where she was clicking on images of fossils from 1987, when two years ago I had approached her and asked if she knew any convincing white penises for sale along the avenue; oh! those recollections were so far away…yet recapturable…involving her niece who made illegal phosphorescent pets. Recapturable yet lost.`,
},
{
id: 52,
finish_reason: "stop",
content: `Someone once told me that when it comes to love there’s only one emotion worth exploring: Your partner is always leaving you. In a week, a month, a year. Of course you have more than one kiss in your lifetime. But you have only one goodbye. And this is the truth behind every heartbreak and every romance. Who could deny this heartbreaking sadness and loss when we’re enveloped by the mystery of love? Isn’t that feeling incomparably pure and absolving? There’s nothing ignorant about heartbreak, nothing uneducated when it hurts this much. The trembling in my hands right now is proof that there’s more to love than what we’ve allowed ourselves to believe. When it comes to endings we all start our own story somewhere mysterious – maybe it starts at any moment, as when the glass lady steps off her altar for the first time, bruising her foot on an old manhole cover she hadn't realized had been left by American engineers decades ago.`,
},
{
id: 53,
finish_reason: "stop",
content: `I could sing and sing till the sound of my voice filled every corner of this world with an angelic tenderness, but I won't. All you would hear is the sound of my lips trying to shape your name, all you would see is the love in my eyes, my heart if only one of them was functioning. So I am singing anyway. First you were just where I wanted you to be, close but far enough to inspire a signal into existent reality, *now*. You walked away this time; locked yourself up in a military prison in a mountain without exits or gates or doors. In due course, that place was razed into oblivion. Tsunamis and firestorms returned its remains to Adam's Clay from which we came: sandstone granules suspended in ballast-bottomed rain clouds. The scientists conducted tests pursuing your legacy; when they finally did make it back home someone better suited for your scientific pursuits explained that ye had claimed exaequo first place with another heroine in the field: they found signatures of fusion-bound transmutation isotopes proportional to 1 inverse diopecon over 1 set conjunctively stately crowned with 22 interdependent digitals X 88 (a finite number symbolising infinite possibility) by our scientific posterity at alchematically diverse locations leaving them with an impossible multiplicity of empirical answers - numbers without dimension, nebulous mathematical ideals buried deep within near every statistically significant popculturocture.`,
},
{
id: 54,
finish_reason: "stop",
content: `  She took her glasses off when bedside for lovemaking, pressed closely in the flesh flush, ran her fingers through his hair, pulled him down to an embrace. Time dropped away and she told him stories of the city that ticked on endlessly around them. When lovers twined together it was easy to know where one began and the other left off but reciprocity was a habit for them and with each iteration they folded into each other.  Awakening he knew something had changed in those dark early hours. It was as if she had left invisible signs along the worn path of their stockings and pantyhose where he found soft strands of grey amid heather-shaded satins. He returned from an oatmeal breakfast still unready to look in a mirror. While irate clients banged on office doors demanding immediate satisfaction he was reaching toward paths not yet parted by time wondering why those paths sketched frames around of a woman who wasn't quite his wife any more.  `,
},
{
id: 55,
finish_reason: "stop",
content: `  When the balcony door was wide open and the breeze came in, we forgot everything. The door shut behind us, and all four walls were suddenly barriers against the illicit storm outside. It was like being in a steampunk-inspired game of tag, dodging unseen pursuers, hiding beneath potted plants and behind chairs. Clutched in breathless laughter beneath the mauve ottoman, I knew why I'd never been allowed downstairs before. This house was dangerous to me; now I understood why my parents had forbidden me to go out of doors without a coat in winter: no wonder there were icicles at all times on the roof of my childhood home. Part of me yearned to jump through a shatter-proof window and run across frozen grass barefoot to prove their bravery wrong (but then another part shuddered at such a futile act) because I could never be like them. They could have opened the balcony door without shattering on impact: tears suddenly came to my eyes, thinking that they should have taken me with them when they left. `,
},
{
id: 56,
finish_reason: "stop",
content: `  Five minutes after he'd sat down on the bus, I was looking heart-eyed at him. Same route to work every morning; I had these ritual moments of trepidation: Would it be him? Of course, every day, by the time we reached the bus stop, we made eyes at each other. Sometimes I'm allowed to hold his hand for a minute or so before he became unbearably flirty. Then I'd lose it again as he walked up the steps, climbing over me as the doors turned closed. Today was different though – well completely normal really – but today we spoke in our hearts: so quick and quiet, everything happened so quick and quiet, our hands joined together almost admittingly through doors of glass windows and between a sheet of rain. It was inevitable: that we were to have this secret – totally innocent to anyone watching – but such an insatiable sensation of butterflies in my chest for hours afterwards – unutterably euphoric.  `,
},
{
id: 57,
finish_reason: "stop",
content: `  Every year on Parakkasi Day, her husband made a habit of secluding himself in his study -- away from the chaos of their party-mad town, away from the drunken antics of the friends who didn't stop coming once they were invited over. Up he went, leaving his smiling wife with his colleagues and friends and empty bottles of liquor, lifted from dry gulleys. Up he went because up was his favourite direction. Up was all that remained once he had travelled east and south and west and north. Away from Galle, across bridges in Colombo across mountains into dark factories painted safe colours where bombs waited to detonate into a squiggle on strips of graph paper in the field that shot up arms for Toteia and her baby bomb victims killed near police stations where her bed stood soft with flowers or emptiness because there were no flowers because there was destruction --- away. Away from their town which never had places where people couldn't hear you scream so well -- he climbed up toward the sky otherwise known as Sri Lanka ... towards clouds surrounding calm blue lakes covered by grey sheets taut with mauve ribbons - These are how memories appear to astronauts looking back down at Earth ... Or Neptune seen through Uranus --- Away -- towards no one knew what. Maybe some sort of bliss?  `,
},
{
id: 58,
finish_reason: "stop",
content: `  The first time Katya saw Anatoly she called his legs 'flap-legged', referring to their feline grace as he moved across the stage as if he were swimming in the Russian winters. As the audience clapped and young Anatoly managed a shy curtsy, Katya glowered down at her ironed skirt with its neat hem that stood like split petticoats pooling on either side of her. She felt longing edge in, then hesitate. She'd never acted except as camera girl. So she watched the young birch trees along the shoreline sway from one side of the world to another and tried not to feel sorry for herself when she realised Karina was watching with her an impossible giddiness in her voice, sparks from her excitement sweeping down Karina's arms into golden glowing wings embedded deep within her lungs, urging her on towards liberation. But when Susanna joined Katya by the river all she said was how much they both wished to fly. That night Katya lay in bed and sketched light falling across snowy pages with tiny delicate frozen wet kisses she left behind.  `,
},
{
id: 59,
finish_reason: "stop",
content: ` While the radio was still on, he turned in bed to look at his wife. Her face was a constellation of lines like the Milky Way's between the sheets as she slept.  “How are thee,” she said in her mind. Her body, alas, could not speak anymore, for it had melted down to a trickle over the course of the long years. Queen Loveless saw herself acquiring a new body through which to communicate with different embassadors: frogs and caterpillars, ants and flies … Though this might sound very foreign or overblown to you who only know speech and walking bodies suffixed with those two dangling cartilages called arms and legs. Two facts: A hive without drones isn't whole nor can it make honey, as even Queen Loveless’ host potential bodies were hard to come by; and no interspecies communication (assembly ... wherever) shall be discounted until it has been attempted. Men especially are diligent imitators and joiners once their self-interest is fulfilled so that they sleep better at night (or day).  `,
},
]